name: gisabo-platform
services:
- name: web
  source_dir: /
  github:
    repo: yeoyedjande/gisabo-v2
    branch: main
  build_command: |
    echo "🚀 Installation des dépendances..."
    npm ci --production=false
    echo "🏗️ Construction de l'application..."
    npm run build
    echo "✅ Build terminé avec succès"
  run_command: node start-prod.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 180
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"
  - key: SQUARE_ENVIRONMENT
    value: production

databases:
- name: gisabo-db
  engine: PG
  version: "15"
  size: basic-xxs
  num_nodes: 1