name: gisabo-platform
services:
- name: web
  source_dir: /
  github:
    repo: yeoyedjande/gisabo-v2
    branch: main
  build_command: |
    npm ci
    npm run build
    echo "📦 Création du dossier server/public et copie des assets..."
    mkdir -p server/public
    cp -r dist/public/* server/public/ 2>/dev/null || echo "Build files copied to server/public"
    cp -r attached_assets server/public/ 2>/dev/null || echo "Assets statiques copiés vers server/public"
    ls -la server/public/
    echo "✅ Build et assets prêts dans server/public/"
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /api/health
    initial_delay_seconds: 120
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"

databases:
- name: gisabo-db
  engine: PG
  version: "15"
  size: db-s-dev-database
  num_nodes: 1