name: gisabo-platform
services:
- name: web
  source_dir: /
  github:
    repo: votre-username/gisabo-platform
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  health_check:
    http_path: /api/health
    initial_delay_seconds: 60
    period_seconds: 10
    timeout_seconds: 5
    failure_threshold: 3
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"

databases:
- name: gisabo-db
  engine: PG
  version: "15"
  size: basic-xxs
  num_nodes: 1