name: gisabo-platform
services:
- name: web
  source_dir: /
  github:
    repo: yeoyedjande/gisabo-v2
    branch: main
  build_command: npm ci && npm run build
  run_command: node start-prod.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 120
    period_seconds: 30
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5000"

databases:
- name: gisabo-db
  engine: PG
  version: "15"
  size: db-s-dev-database
  num_nodes: 1